remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  is_project_page: false

title: ourAMSTERcaps 2025 - July 16-18, Amsterdam, Netherlands
description: European Research Meeting on Automated Planning and Scheduling
